spring.datasource.url=jdbc:mysql://semana8.cp1ra8k6pdqn.us-east-1.rds.amazonaws.com:3306/Sucursal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.username=admin
spring.datasource.password=DevopsSemana8
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/api-docs
